config/routes.rb
Rails.application.routes.draw do
  resources :photos do
    post :upload, on: :collection
  end

end

app/models/google_cloud_vision.rb
class GoogleCloudVision
  attr_accessor :endpoint_uri, :file_path, :detection_type

  def initialize(file_path, detection_type)
    @endpoint_uri = "https://vision.googleapis.com/v1alpha1/images:annotate?key=#{ENV['SERVER_KEY']}"
    @file_path = file_path
    @detection_type = detection_type
  end

  def request
    http_client = HTTPClient.new
    content = Base64.strict_encode64(File.new(file_path, 'rb').read)
    response = http_client.post_content(endpoint_uri, request_json(content), 'Content-Type' => 'application/json')
    result_parse(response)
  end

  private

  def request_json(content)
    {
      requests: [{
        image: {
          content: content
        },
        features: [{
          type: "#{detection_type.upcase}_DETECTION",
          maxResults: 10
        }]
      }]
    }.to_json
  end

  def result_parse(response)
    result = JSON.parse(response)['responses'].first
    case detection_type
    when 'label'
      label = result['labelAnnotations'].first
      result = "これは、#{label['description']}です。"
    when 'text'
      text = result['textAnnotations'].first
      result = "これは、#{text['locale']}です。\n-----\n#{text['description']}"
    end
    result
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  permits :file, :detection_type

  def new
    @photo = Photo.new
  end

  def upload(photo, detection_type)
    @photo = Photo.new(photo)
    @detection_type = detection_type
    @result = GoogleCloudVision.new(@photo.file.path, detection_type).request
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoogleVsion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/new.html.erb
<h2>ファイルアップロード</h2>
<%= form_for @photo, url: upload_photos_path, html: { multipart: true } do |f| %>
  <div>
    <label>ファイル</label>
    <%= f.file_field :file %>
  </div>
  <div>
    <label>認識タイプ</label>
    <%= select_tag 'detection_type', options_for_select([['Label', 'label'], ['Text', 'text']]) %>
  </div>
  <div>
    <%= f.submit 'アップロード' %>
  </div>
<% end %>

app/views/photos/upload.html.erb
<h2>結果</h2>
<%= image_tag @photo.file.url, width: '400px' %>
<br>
<pre>
<%= @result %>
</pre>
<hr/>
<%= link_to '戻る', new_photo_path %>